# ~/.config/waybar/config.yaml

layer: "bottom"
position: "top"
height: 31
spacing: 5
exclusive: true
font: "Arimo Nerd Font 12"
scripts_path: /home/gdanko/.config/waybar

static_modules:
  - name: cpu-usage
    enabled: true
    interval: 3
  - name: dropbox-status
    enabled: true
    interval: 3
  - name: memory-usage
    enabled: true
    interval: 3
    unit: auto
  - name: plex-status
    enabled: false
    interval: 60
    ip: "{key:plex_ip}"
    port: 32400
    api_key: "{key:plex_api_token}"
  - name: quakes
    enabled: false
    interval: 1800
    limit: 20
    radius: 100m
    magnitude: 0.1
  - name: speedtest
    enabled: true
    interval: 300

disk_consumers:
  enabled: true
  interval: 3600
  unit: auto
  paths:
    - "~"
    - /work

filesystem_usage:
  enabled: true
  show_stats: true
  interval: 60
  debug: false
  unit: auto
  mountpoints:
    - /
    - /work

network_throughput:
  enabled: true
  interval: 10
  interfaces:
    - wlo1

software_updates:
  enabled: true
  interval: 1800
  package_types:
    - dnf
    - flatpak
    - snap

stock_quotes:
  enabled: true
  interval: 900
  symbols:
    - AAPL
    - GOOG
    - NOW

wifi_status:
  enabled: true
  interval: 10
  interfaces:
    - wlo1

weather:
  enabled: true
  interval: 600
  api_key: "{key:wapi_key}"
  locations:
    - "San Diego, CA, US"
    - "Chula Vista, CA, US"
    - "Yucaipa, CA, US"
